/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as DiretorioRouteImport } from './routes/diretorio'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin.perfis'
import { Route as AuthenticatedPerfilEditRouteImport } from './routes/_authenticated/perfil.edit'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as AuthenticatedAdminPerfisIdRouteImport } from './routes/_authenticated/admin.perfis.$id'
import { Route as ApiPublicCronSyncSocialRouteImport } from './routes/api/public/cron/sync-social'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const DiretorioRoute = DiretorioRouteImport.update({
  id: '/diretorio',
  path: '/diretorio',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/admin/perfis',
    path: '/admin/perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilEditRoute = AuthenticatedPerfilEditRouteImport.update({
  id: '/perfil/edit',
  path: '/perfil/edit',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPerfisIdRoute =
  AuthenticatedAdminPerfisIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedAdminPerfisRoute,
  } as any)
const ApiPublicCronSyncSocialRoute = ApiPublicCronSyncSocialRouteImport.update({
  id: '/api/public/cron/sync-social',
  path: '/api/public/cron/sync-social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/diretorio': typeof DiretorioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRouteWithChildren
  '/perfil/edit': typeof AuthenticatedPerfilEditRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/admin/perfis/$id': typeof AuthenticatedAdminPerfisIdRoute
  '/api/public/cron/sync-social': typeof ApiPublicCronSyncSocialRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/diretorio': typeof DiretorioRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRouteWithChildren
  '/perfil/edit': typeof AuthenticatedPerfilEditRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/admin/perfis/$id': typeof AuthenticatedAdminPerfisIdRoute
  '/api/public/cron/sync-social': typeof ApiPublicCronSyncSocialRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/auth': typeof AuthRoute
  '/diretorio': typeof DiretorioRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRouteWithChildren
  '/_authenticated/perfil/edit': typeof AuthenticatedPerfilEditRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/_authenticated/admin/perfis/$id': typeof AuthenticatedAdminPerfisIdRoute
  '/api/public/cron/sync-social': typeof ApiPublicCronSyncSocialRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/auth'
    | '/diretorio'
    | '/dashboard'
    | '/admin/perfis'
    | '/perfil/edit'
    | '/api/public/sitemap.xml'
    | '/admin/perfis/$id'
    | '/api/public/cron/sync-social'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/auth'
    | '/diretorio'
    | '/dashboard'
    | '/admin/perfis'
    | '/perfil/edit'
    | '/api/public/sitemap.xml'
    | '/admin/perfis/$id'
    | '/api/public/cron/sync-social'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/auth'
    | '/diretorio'
    | '/_authenticated/dashboard'
    | '/_authenticated/admin/perfis'
    | '/_authenticated/perfil/edit'
    | '/api/public/sitemap.xml'
    | '/_authenticated/admin/perfis/$id'
    | '/api/public/cron/sync-social'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AuthRoute: typeof AuthRoute
  DiretorioRoute: typeof DiretorioRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicCronSyncSocialRoute: typeof ApiPublicCronSyncSocialRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diretorio': {
      id: '/diretorio'
      path: '/diretorio'
      fullPath: '/diretorio'
      preLoaderRoute: typeof DiretorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil/edit': {
      id: '/_authenticated/perfil/edit'
      path: '/perfil/edit'
      fullPath: '/perfil/edit'
      preLoaderRoute: typeof AuthenticatedPerfilEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/perfis/$id': {
      id: '/_authenticated/admin/perfis/$id'
      path: '/$id'
      fullPath: '/admin/perfis/$id'
      preLoaderRoute: typeof AuthenticatedAdminPerfisIdRouteImport
      parentRoute: typeof AuthenticatedAdminPerfisRoute
    }
    '/api/public/cron/sync-social': {
      id: '/api/public/cron/sync-social'
      path: '/api/public/cron/sync-social'
      fullPath: '/api/public/cron/sync-social'
      preLoaderRoute: typeof ApiPublicCronSyncSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminPerfisRouteChildren {
  AuthenticatedAdminPerfisIdRoute: typeof AuthenticatedAdminPerfisIdRoute
}

const AuthenticatedAdminPerfisRouteChildren: AuthenticatedAdminPerfisRouteChildren =
  {
    AuthenticatedAdminPerfisIdRoute: AuthenticatedAdminPerfisIdRoute,
  }

const AuthenticatedAdminPerfisRouteWithChildren =
  AuthenticatedAdminPerfisRoute._addFileChildren(
    AuthenticatedAdminPerfisRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRouteWithChildren
  AuthenticatedPerfilEditRoute: typeof AuthenticatedPerfilEditRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRouteWithChildren,
  AuthenticatedPerfilEditRoute: AuthenticatedPerfilEditRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AuthRoute: AuthRoute,
  DiretorioRoute: DiretorioRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicCronSyncSocialRoute: ApiPublicCronSyncSocialRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
