/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SlugRouteImport } from './routes/$slug'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AcademiaRouteImport } from './routes/academia'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CodigoDeCondutaRouteImport } from './routes/codigo-de-conduta'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VitrineRouteImport } from './routes/vitrine'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as CriadorSlugRouteImport } from './routes/criador.$slug'
import { Route as PerfilSlugRouteImport } from './routes/perfil.$slug'
import { Route as AuthenticatedAdminPerfisRouteImport } from './routes/_authenticated/admin.perfis'
import { Route as ApiPublicSitemapDotxmlRouteImport } from './routes/api/public/sitemap[.]xml'
import { Route as AuthenticatedAdminPerfisIdRouteImport } from './routes/_authenticated/admin.perfis_.$id'
import { Route as ApiPublicCronSyncSocialRouteImport } from './routes/api/public/cron/sync-social'
import { Route as ApiPublicImgSplatRouteImport } from './routes/api/public/img.$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SlugRoute = SlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademiaRoute = AcademiaRouteImport.update({
  id: '/academia',
  path: '/academia',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CodigoDeCondutaRoute = CodigoDeCondutaRouteImport.update({
  id: '/codigo-de-conduta',
  path: '/codigo-de-conduta',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VitrineRoute = VitrineRouteImport.update({
  id: '/vitrine',
  path: '/vitrine',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CriadorSlugRoute = CriadorSlugRouteImport.update({
  id: '/criador/$slug',
  path: '/criador/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilSlugRoute = PerfilSlugRouteImport.update({
  id: '/perfil/$slug',
  path: '/perfil/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPerfisRoute =
  AuthenticatedAdminPerfisRouteImport.update({
    id: '/admin/perfis',
    path: '/admin/perfis',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicSitemapDotxmlRoute = ApiPublicSitemapDotxmlRouteImport.update({
  id: '/api/public/sitemap.xml',
  path: '/api/public/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminPerfisIdRoute =
  AuthenticatedAdminPerfisIdRouteImport.update({
    id: '/admin/perfis_/$id',
    path: '/admin/perfis/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicCronSyncSocialRoute = ApiPublicCronSyncSocialRouteImport.update({
  id: '/api/public/cron/sync-social',
  path: '/api/public/cron/sync-social',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImgSplatRoute = ApiPublicImgSplatRouteImport.update({
  id: '/api/public/img/$',
  path: '/api/public/img/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/academia': typeof AcademiaRoute
  '/auth': typeof AuthRoute
  '/codigo-de-conduta': typeof CodigoDeCondutaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vitrine': typeof VitrineRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/criador/$slug': typeof CriadorSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/admin/perfis/$id': typeof AuthenticatedAdminPerfisIdRoute
  '/api/public/cron/sync-social': typeof ApiPublicCronSyncSocialRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$slug': typeof SlugRoute
  '/academia': typeof AcademiaRoute
  '/auth': typeof AuthRoute
  '/codigo-de-conduta': typeof CodigoDeCondutaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vitrine': typeof VitrineRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/criador/$slug': typeof CriadorSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/admin/perfis/$id': typeof AuthenticatedAdminPerfisIdRoute
  '/api/public/cron/sync-social': typeof ApiPublicCronSyncSocialRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/$slug': typeof SlugRoute
  '/academia': typeof AcademiaRoute
  '/auth': typeof AuthRoute
  '/codigo-de-conduta': typeof CodigoDeCondutaRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/vitrine': typeof VitrineRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/criador/$slug': typeof CriadorSlugRoute
  '/perfil/$slug': typeof PerfilSlugRoute
  '/_authenticated/admin/perfis': typeof AuthenticatedAdminPerfisRoute
  '/api/public/sitemap.xml': typeof ApiPublicSitemapDotxmlRoute
  '/_authenticated/admin/perfis_/$id': typeof AuthenticatedAdminPerfisIdRoute
  '/api/public/cron/sync-social': typeof ApiPublicCronSyncSocialRoute
  '/api/public/img/$': typeof ApiPublicImgSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$slug'
    | '/academia'
    | '/auth'
    | '/codigo-de-conduta'
    | '/sitemap.xml'
    | '/vitrine'
    | '/dashboard'
    | '/criador/$slug'
    | '/perfil/$slug'
    | '/admin/perfis'
    | '/api/public/sitemap.xml'
    | '/admin/perfis/$id'
    | '/api/public/cron/sync-social'
    | '/api/public/img/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$slug'
    | '/academia'
    | '/auth'
    | '/codigo-de-conduta'
    | '/sitemap.xml'
    | '/vitrine'
    | '/dashboard'
    | '/criador/$slug'
    | '/perfil/$slug'
    | '/admin/perfis'
    | '/api/public/sitemap.xml'
    | '/admin/perfis/$id'
    | '/api/public/cron/sync-social'
    | '/api/public/img/$'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/$slug'
    | '/academia'
    | '/auth'
    | '/codigo-de-conduta'
    | '/sitemap.xml'
    | '/vitrine'
    | '/_authenticated/dashboard'
    | '/criador/$slug'
    | '/perfil/$slug'
    | '/_authenticated/admin/perfis'
    | '/api/public/sitemap.xml'
    | '/_authenticated/admin/perfis_/$id'
    | '/api/public/cron/sync-social'
    | '/api/public/img/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  SlugRoute: typeof SlugRoute
  AcademiaRoute: typeof AcademiaRoute
  AuthRoute: typeof AuthRoute
  CodigoDeCondutaRoute: typeof CodigoDeCondutaRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VitrineRoute: typeof VitrineRoute
  CriadorSlugRoute: typeof CriadorSlugRoute
  PerfilSlugRoute: typeof PerfilSlugRoute
  ApiPublicSitemapDotxmlRoute: typeof ApiPublicSitemapDotxmlRoute
  ApiPublicCronSyncSocialRoute: typeof ApiPublicCronSyncSocialRoute
  ApiPublicImgSplatRoute: typeof ApiPublicImgSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$slug': {
      id: '/$slug'
      path: '/$slug'
      fullPath: '/$slug'
      preLoaderRoute: typeof SlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academia': {
      id: '/academia'
      path: '/academia'
      fullPath: '/academia'
      preLoaderRoute: typeof AcademiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codigo-de-conduta': {
      id: '/codigo-de-conduta'
      path: '/codigo-de-conduta'
      fullPath: '/codigo-de-conduta'
      preLoaderRoute: typeof CodigoDeCondutaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vitrine': {
      id: '/vitrine'
      path: '/vitrine'
      fullPath: '/vitrine'
      preLoaderRoute: typeof VitrineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/criador/$slug': {
      id: '/criador/$slug'
      path: '/criador/$slug'
      fullPath: '/criador/$slug'
      preLoaderRoute: typeof CriadorSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil/$slug': {
      id: '/perfil/$slug'
      path: '/perfil/$slug'
      fullPath: '/perfil/$slug'
      preLoaderRoute: typeof PerfilSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/perfis': {
      id: '/_authenticated/admin/perfis'
      path: '/admin/perfis'
      fullPath: '/admin/perfis'
      preLoaderRoute: typeof AuthenticatedAdminPerfisRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/sitemap.xml': {
      id: '/api/public/sitemap.xml'
      path: '/api/public/sitemap.xml'
      fullPath: '/api/public/sitemap.xml'
      preLoaderRoute: typeof ApiPublicSitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/perfis_/$id': {
      id: '/_authenticated/admin/perfis_/$id'
      path: '/admin/perfis/$id'
      fullPath: '/admin/perfis/$id'
      preLoaderRoute: typeof AuthenticatedAdminPerfisIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/cron/sync-social': {
      id: '/api/public/cron/sync-social'
      path: '/api/public/cron/sync-social'
      fullPath: '/api/public/cron/sync-social'
      preLoaderRoute: typeof ApiPublicCronSyncSocialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/img/$': {
      id: '/api/public/img/$'
      path: '/api/public/img/$'
      fullPath: '/api/public/img/$'
      preLoaderRoute: typeof ApiPublicImgSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedAdminPerfisRoute: typeof AuthenticatedAdminPerfisRoute
  AuthenticatedAdminPerfisIdRoute: typeof AuthenticatedAdminPerfisIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedAdminPerfisRoute: AuthenticatedAdminPerfisRoute,
  AuthenticatedAdminPerfisIdRoute: AuthenticatedAdminPerfisIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  SlugRoute: SlugRoute,
  AcademiaRoute: AcademiaRoute,
  AuthRoute: AuthRoute,
  CodigoDeCondutaRoute: CodigoDeCondutaRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VitrineRoute: VitrineRoute,
  CriadorSlugRoute: CriadorSlugRoute,
  PerfilSlugRoute: PerfilSlugRoute,
  ApiPublicSitemapDotxmlRoute: ApiPublicSitemapDotxmlRoute,
  ApiPublicCronSyncSocialRoute: ApiPublicCronSyncSocialRoute,
  ApiPublicImgSplatRoute: ApiPublicImgSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
